EWPP-930: Drupal 9 compatibility fixes.
openeuropa/oe_time_caching pull request #8
Opened 2021-05-11 11:51 UTC by 22Alexandra

2021-05-12 06:06 UTC, drishu submitted a review, later dismissed

2021-05-12 07:34 UTC, upchuk requested changes
You are missing changes in the phpunit.xml.dist file, grump (status A paraitre should be orderable)

Please check the other tickets and lets bring these components up to date.

2021-05-12 07:34 UTC, upchuk commented on composer.json
> +        "nesbot/carbon": "^2.47"
Why are you increasing this (and all other deps that don't have to be increased)?

2021-05-12 15:56 UTC, yenyasinn reviewed
Behat tests aren't used here but in any case please wrap strings by quote as in https://github.com/openeuropa/oe_multilingual/pull/121/files#diff-50059421b2806d799959ec59ad6bfa4c6bb1156415eb804f1bbf62c77cae6b90

2021-05-12 15:56 UTC, yenyasinn commented on oe_time_caching.info.yml
>  package: OpenEuropa
Would be good to wrap module's name and description by single quote as in https://github.com/openeuropa/oe_webtools/pull/156/files#diff-c61f63280f6689204a18fcb67a674514314c749361707af3cd04340c1af1fadc.

2021-05-12 15:56 UTC, yenyasinn commented on composer.json
>          "guzzlehttp/guzzle": "~6.3",
```suggestion
```
We don't need `"guzzlehttp/guzzle": "~6.3",` because it is already the dependency of the Drupal core

2021-05-13 08:11 UTC, yenyasinn approved these changes

2021-05-17 08:27 UTC, nagyad approved these changes

2021-05-18 06:11 UTC, upchuk approved these changes

2021-05-18 06:11 UTC, merged